# Build step #1: build the React front end
FROM node:16-alpine as build-step
WORKDIR /
ENV PATH /node_modules/.bin:$PATH
COPY frontend/package.json ./
COPY frontend/package-lock.json ./
COPY frontend/src ./src
COPY frontend/public ./public
COPY frontend/node_modules ./node_modules
RUN npm install
RUN npm run build

# Build step #2: build an nginx container
FROM nginx:stable-alpine
COPY --from=build-step /build /usr/share/nginx/html
COPY ./nginx.default.conf /etc/nginx/conf.d/default.conf
