services:
  wsgi:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: react-flask-app-api
    volumes:
      - ./backend/logs:/backend/logs
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: react-flask-app-client
    ports:
      - "80:80"
